### ISSUE TITLE
Intro video doesn't play on Linux

### ISSUE THREAD

**Issue by Jazcash** [Jazcash/bar-lobby#21]
Tested a fresh minimal installation of Ubuntu 22.04 in VirtualBox and intro video doesn't play at all, just renders black with no audio. Can still be skipped so not a blocker.

Possibly just an issue related to virtualisation. Would be handy if someone running Linux natively could confirm if this is actually an issue.

**Comment by p2004a** [comment]
Didn't you by any chance just forgot to do `git lfs pull` to make sure that intro is actually fetched? Because that's how it worked for me, I saw a black with no audio, noticed that video file is only a few bytes large and it has something about git lfs in it, and after `git lfs pull` it worked fine.

![Screenshot from 2022-07-02 00-24-41](https://user-images.githubusercontent.com/2212599/176974370-576950a0-eaae-49ce-9a51-a62305624696.png)

**Comment by Jazcash** [comment]
> Didn't you by any chance just forgot to do `git lfs pull` to make sure that intro is actually fetched? Because that's how it worked for me, I saw a black screen with no audio, noticed that video file is only a few bytes large and it has something about git lfs in it, and after `git lfs pull` it worked fine.
> 
> ![Screenshot from 2022-07-02 00-24-41](https://user-images.githubusercontent.com/2212599/176974370-576950a0-eaae-49ce-9a51-a62305624696.png)

Ha, that was probably it

**Comment by Jazcash** [comment]
Reopening because somebody is having the same issue on Fedora:

> I thought I would give this a try today. I used the AppImage file. All I see is a black screen. The command line shows these error:
> libva error: /usr/lib64/dri/i965_drv_video.so init failed
[5251:0714/053200.182688:ERROR:sandbox_linux.cc(376)] InitializeSandbox() called with multiple threads in process gpu-process.
> I am on Fedora 36.

**Comment by p2004a** [comment]
I'm pretty sure that it's just video asset no being included again and it's probably not specific to linux.

Size of files in https://github.com/Jazcash/bar-lobby/releases/tag/v0.6.5 is only 140-189MiB, the video file https://github.com/Jazcash/bar-lobby/blob/master/src/assets/videos/intro.mp4 is 160MiB: It's not being included in the packages.

Probably the https://github.com/Jazcash/bar-lobby/blob/master/.github/workflows/build.yml#L16 just doesn't fetch files from LFS.
